runs:
    using: 'composite'
    steps:
        - uses: actions/setup-java@v3
            with:
            using: "composite"
                java-version: '17'
                distribution: 'temurin'
                cache: maven
