runs:
    using: "composite"
    steps:
        - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
        using: "composite"
            java-version: '17'
            distribution: 'temurin'
            cache: maven
